<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>LanguageServer</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
    <ApplicationIcon>vscode.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="test\**" />
    <Compile Remove="_verify\**" />
    <EmbeddedResource Remove="test\**" />
    <EmbeddedResource Remove="_verify\**" />
    <None Remove="test\**" />
    <None Remove="_verify\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="vscode.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\GCModeller\src\R-sharp\R#\Rsharp-netcore5.vbproj" />
    <ProjectReference Include="..\..\..\GCModeller\src\runtime\httpd\src\Flute\Flute.NET5.vbproj" />
    <ProjectReference Include="..\..\..\GCModeller\src\runtime\sciBASIC#\Microsoft.VisualBasic.Core\src\Core.vbproj" />
    <ProjectReference Include="..\..\..\GCModeller\src\runtime\sciBASIC#\mime\application%json\JSON-netcore5.vbproj" />
    <ProjectReference Include="..\..\..\GCModeller\src\runtime\sciBASIC#\vs_solutions\dev\VisualStudio\VisualStudio.NET5.vbproj" />
  </ItemGroup>

</Project>
