//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using RibbonLib;
using RibbonLib.Controls;

namespace RibbonLib.Controls
{
    partial class RibbonItems
    {
        private static class Cmd
        {
            public const uint cmdButtonNew = 2;
            public const uint cmdButtonOpen = 11;
            public const uint cmdButtonAbout = 4;
            public const uint cmdButtonExit = 3;
            public const uint cmdButtonSave = 5;
            public const uint cmdRibbonEditor = 7;
            public const uint cmdMenuEditor = 8;
            public const uint cmdGroupEditor = 9;
            public const uint cmdButtonGotoLine = 18;
            public const uint cmdButtonEditorDiff = 17;
            public const uint cmdButtonEditorSymbols = 16;
            public const uint cmdGroupEditorMics = 19;
            public const uint cmdButtonEditorTheme = 15;
            public const uint cmdMenuEdit = 14;
            public const uint cmdGroupFile = 12;
            public const uint cmdGroupSave = 13;
            public const uint cmdButtonSaveAs = 10;
            public const uint cmdButtonSaveAll = 6;
        }

        // ContextPopup CommandName

        public Ribbon Ribbon { get; private set; }
        public RibbonButton ButtonNew { get; private set; }
        public RibbonButton ButtonOpen { get; private set; }
        public RibbonButton ButtonAbout { get; private set; }
        public RibbonButton ButtonExit { get; private set; }
        public RibbonButton ButtonSave { get; private set; }
        public RibbonTabGroup RibbonEditor { get; private set; }
        public RibbonTab MenuEditor { get; private set; }
        public RibbonGroup GroupEditor { get; private set; }
        public RibbonButton ButtonGotoLine { get; private set; }
        public RibbonButton ButtonEditorDiff { get; private set; }
        public RibbonButton ButtonEditorSymbols { get; private set; }
        public RibbonGroup GroupEditorMics { get; private set; }
        public RibbonButton ButtonEditorTheme { get; private set; }
        public RibbonTab MenuEdit { get; private set; }
        public RibbonGroup GroupFile { get; private set; }
        public RibbonGroup GroupSave { get; private set; }
        public RibbonButton ButtonSaveAs { get; private set; }
        public RibbonButton ButtonSaveAll { get; private set; }

        public RibbonItems(Ribbon ribbon)
        {
            if (ribbon == null)
                throw new ArgumentNullException(nameof(ribbon), "Parameter is null");
            this.Ribbon = ribbon;
            ButtonNew = new RibbonButton(ribbon, Cmd.cmdButtonNew);
            ButtonOpen = new RibbonButton(ribbon, Cmd.cmdButtonOpen);
            ButtonAbout = new RibbonButton(ribbon, Cmd.cmdButtonAbout);
            ButtonExit = new RibbonButton(ribbon, Cmd.cmdButtonExit);
            ButtonSave = new RibbonButton(ribbon, Cmd.cmdButtonSave);
            RibbonEditor = new RibbonTabGroup(ribbon, Cmd.cmdRibbonEditor);
            MenuEditor = new RibbonTab(ribbon, Cmd.cmdMenuEditor);
            GroupEditor = new RibbonGroup(ribbon, Cmd.cmdGroupEditor);
            ButtonGotoLine = new RibbonButton(ribbon, Cmd.cmdButtonGotoLine);
            ButtonEditorDiff = new RibbonButton(ribbon, Cmd.cmdButtonEditorDiff);
            ButtonEditorSymbols = new RibbonButton(ribbon, Cmd.cmdButtonEditorSymbols);
            GroupEditorMics = new RibbonGroup(ribbon, Cmd.cmdGroupEditorMics);
            ButtonEditorTheme = new RibbonButton(ribbon, Cmd.cmdButtonEditorTheme);
            MenuEdit = new RibbonTab(ribbon, Cmd.cmdMenuEdit);
            GroupFile = new RibbonGroup(ribbon, Cmd.cmdGroupFile);
            GroupSave = new RibbonGroup(ribbon, Cmd.cmdGroupSave);
            ButtonSaveAs = new RibbonButton(ribbon, Cmd.cmdButtonSaveAs);
            ButtonSaveAll = new RibbonButton(ribbon, Cmd.cmdButtonSaveAll);
        }

    }
}
