//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using RibbonLib;
using RibbonLib.Controls;

namespace RibbonLib.Controls
{
    partial class RibbonItems
    {
        private static class Cmd
        {
            public const uint cmdButtonNew = 2;
            public const uint cmdButtonOpen = 11;
            public const uint cmdButtonSettings = 25;
            public const uint cmdButtonLicense = 27;
            public const uint cmdButtonAbout = 4;
            public const uint cmdButtonExit = 3;
            public const uint cmdButtonStartPage = 20;
            public const uint cmdButtonSave = 5;
            public const uint cmdRibbonEditor = 7;
            public const uint cmdMenuEditor = 8;
            public const uint cmdGroupCodeFile = 23;
            public const uint cmdButtonCodeFormatted = 30;
            public const uint cmdButtonEditorReload = 31;
            public const uint cmdButtonSaveCodeFile = 22;
            public const uint cmdButtonSaveAsCodeFile = 24;
            public const uint cmdGroupEditor = 9;
            public const uint cmdButtonGotoLine = 18;
            public const uint cmdButtonEditorDiff = 17;
            public const uint cmdButtonEditorSymbols = 16;
            public const uint cmdButtonEditorMiniMap = 26;
            public const uint cmdGroupEditorMics = 19;
            public const uint cmdButtonDeepSeekLLM = 29;
            public const uint cmdButtonEditorTheme = 15;
            public const uint cmdMenuEdit = 14;
            public const uint cmdGroupFile = 12;
            public const uint cmdGroupSave = 13;
            public const uint cmdButtonSaveAs = 10;
            public const uint cmdButtonSaveAll = 6;
            public const uint cmdGroupWorkbench = 21;
            public const uint cmdButtonOutputTool = 32;
            public const uint cmdTabConsole = 37;
            public const uint cmdGroupConsole = 36;
            public const uint cmdButtonConsole = 28;
            public const uint cmdButtonSsh = 35;
            public const uint cmdGroupSshSessions = 38;
            public const uint cmdButtonRemoteSessions = 39;
            public const uint cmdTabInformation = 33;
            public const uint cmdGroupInformation = 34;
        }

        // ContextPopup CommandName

        public Ribbon Ribbon { get; private set; }
        public RibbonButton ButtonNew { get; private set; }
        public RibbonButton ButtonOpen { get; private set; }
        public RibbonButton ButtonSettings { get; private set; }
        public RibbonButton ButtonLicense { get; private set; }
        public RibbonButton ButtonAbout { get; private set; }
        public RibbonButton ButtonExit { get; private set; }
        public RibbonButton ButtonStartPage { get; private set; }
        public RibbonButton ButtonSave { get; private set; }
        public RibbonTabGroup RibbonEditor { get; private set; }
        public RibbonTab MenuEditor { get; private set; }
        public RibbonGroup GroupCodeFile { get; private set; }
        public RibbonButton ButtonCodeFormatted { get; private set; }
        public RibbonButton ButtonEditorReload { get; private set; }
        public RibbonButton ButtonSaveCodeFile { get; private set; }
        public RibbonButton ButtonSaveAsCodeFile { get; private set; }
        public RibbonGroup GroupEditor { get; private set; }
        public RibbonButton ButtonGotoLine { get; private set; }
        public RibbonButton ButtonEditorDiff { get; private set; }
        public RibbonButton ButtonEditorSymbols { get; private set; }
        public RibbonButton ButtonEditorMiniMap { get; private set; }
        public RibbonGroup GroupEditorMics { get; private set; }
        public RibbonButton ButtonDeepSeekLLM { get; private set; }
        public RibbonButton ButtonEditorTheme { get; private set; }
        public RibbonTab MenuEdit { get; private set; }
        public RibbonGroup GroupFile { get; private set; }
        public RibbonGroup GroupSave { get; private set; }
        public RibbonButton ButtonSaveAs { get; private set; }
        public RibbonButton ButtonSaveAll { get; private set; }
        public RibbonGroup GroupWorkbench { get; private set; }
        public RibbonButton ButtonOutputTool { get; private set; }
        public RibbonTab TabConsole { get; private set; }
        public RibbonGroup GroupConsole { get; private set; }
        public RibbonButton ButtonConsole { get; private set; }
        public RibbonButton ButtonSsh { get; private set; }
        public RibbonGroup GroupSshSessions { get; private set; }
        public RibbonButton ButtonRemoteSessions { get; private set; }
        public RibbonTab TabInformation { get; private set; }
        public RibbonGroup GroupInformation { get; private set; }

        public RibbonItems(Ribbon ribbon)
        {
            if (ribbon == null)
                throw new ArgumentNullException(nameof(ribbon), "Parameter is null");
            this.Ribbon = ribbon;
            ButtonNew = new RibbonButton(ribbon, Cmd.cmdButtonNew);
            ButtonOpen = new RibbonButton(ribbon, Cmd.cmdButtonOpen);
            ButtonSettings = new RibbonButton(ribbon, Cmd.cmdButtonSettings);
            ButtonLicense = new RibbonButton(ribbon, Cmd.cmdButtonLicense);
            ButtonAbout = new RibbonButton(ribbon, Cmd.cmdButtonAbout);
            ButtonExit = new RibbonButton(ribbon, Cmd.cmdButtonExit);
            ButtonStartPage = new RibbonButton(ribbon, Cmd.cmdButtonStartPage);
            ButtonSave = new RibbonButton(ribbon, Cmd.cmdButtonSave);
            RibbonEditor = new RibbonTabGroup(ribbon, Cmd.cmdRibbonEditor);
            MenuEditor = new RibbonTab(ribbon, Cmd.cmdMenuEditor);
            GroupCodeFile = new RibbonGroup(ribbon, Cmd.cmdGroupCodeFile);
            ButtonCodeFormatted = new RibbonButton(ribbon, Cmd.cmdButtonCodeFormatted);
            ButtonEditorReload = new RibbonButton(ribbon, Cmd.cmdButtonEditorReload);
            ButtonSaveCodeFile = new RibbonButton(ribbon, Cmd.cmdButtonSaveCodeFile);
            ButtonSaveAsCodeFile = new RibbonButton(ribbon, Cmd.cmdButtonSaveAsCodeFile);
            GroupEditor = new RibbonGroup(ribbon, Cmd.cmdGroupEditor);
            ButtonGotoLine = new RibbonButton(ribbon, Cmd.cmdButtonGotoLine);
            ButtonEditorDiff = new RibbonButton(ribbon, Cmd.cmdButtonEditorDiff);
            ButtonEditorSymbols = new RibbonButton(ribbon, Cmd.cmdButtonEditorSymbols);
            ButtonEditorMiniMap = new RibbonButton(ribbon, Cmd.cmdButtonEditorMiniMap);
            GroupEditorMics = new RibbonGroup(ribbon, Cmd.cmdGroupEditorMics);
            ButtonDeepSeekLLM = new RibbonButton(ribbon, Cmd.cmdButtonDeepSeekLLM);
            ButtonEditorTheme = new RibbonButton(ribbon, Cmd.cmdButtonEditorTheme);
            MenuEdit = new RibbonTab(ribbon, Cmd.cmdMenuEdit);
            GroupFile = new RibbonGroup(ribbon, Cmd.cmdGroupFile);
            GroupSave = new RibbonGroup(ribbon, Cmd.cmdGroupSave);
            ButtonSaveAs = new RibbonButton(ribbon, Cmd.cmdButtonSaveAs);
            ButtonSaveAll = new RibbonButton(ribbon, Cmd.cmdButtonSaveAll);
            GroupWorkbench = new RibbonGroup(ribbon, Cmd.cmdGroupWorkbench);
            ButtonOutputTool = new RibbonButton(ribbon, Cmd.cmdButtonOutputTool);
            TabConsole = new RibbonTab(ribbon, Cmd.cmdTabConsole);
            GroupConsole = new RibbonGroup(ribbon, Cmd.cmdGroupConsole);
            ButtonConsole = new RibbonButton(ribbon, Cmd.cmdButtonConsole);
            ButtonSsh = new RibbonButton(ribbon, Cmd.cmdButtonSsh);
            GroupSshSessions = new RibbonGroup(ribbon, Cmd.cmdGroupSshSessions);
            ButtonRemoteSessions = new RibbonButton(ribbon, Cmd.cmdButtonRemoteSessions);
            TabInformation = new RibbonTab(ribbon, Cmd.cmdTabInformation);
            GroupInformation = new RibbonGroup(ribbon, Cmd.cmdGroupInformation);
        }

    }
}
