'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports RibbonLib
Imports RibbonLib.Controls

Namespace RibbonLib.Controls
    Partial Class RibbonItems
        Private Class Cmd
            Public Const cmdButtonNew As UInteger = 2
            Public Const cmdButtonOpen As UInteger = 11
            Public Const cmdButtonAbout As UInteger = 4
            Public Const cmdButtonExit As UInteger = 3
            Public Const cmdButtonStartPage As UInteger = 20
            Public Const cmdButtonSave As UInteger = 5
            Public Const cmdRibbonEditor As UInteger = 7
            Public Const cmdMenuEditor As UInteger = 8
            Public Const cmdGroupCodeFile As UInteger = 23
            Public Const cmdButtonSaveCodeFile As UInteger = 22
            Public Const cmdGroupEditor As UInteger = 9
            Public Const cmdButtonGotoLine As UInteger = 18
            Public Const cmdButtonEditorDiff As UInteger = 17
            Public Const cmdButtonEditorSymbols As UInteger = 16
            Public Const cmdGroupEditorMics As UInteger = 19
            Public Const cmdButtonEditorTheme As UInteger = 15
            Public Const cmdMenuEdit As UInteger = 14
            Public Const cmdGroupFile As UInteger = 12
            Public Const cmdGroupSave As UInteger = 13
            Public Const cmdButtonSaveAs As UInteger = 10
            Public Const cmdButtonSaveAll As UInteger = 6
            Public Const cmdGroupWorkbench As UInteger = 21
        End Class

        ' ContextPopup CommandName

        Private _ribbon As Ribbon
        Public ReadOnly Property Ribbon As Ribbon
            Get
                Return _ribbon
            End Get
        End Property
        Private _ButtonNew As RibbonButton
        Public ReadOnly Property ButtonNew As RibbonButton
            Get
                Return _ButtonNew
            End Get
        End Property
        Private _ButtonOpen As RibbonButton
        Public ReadOnly Property ButtonOpen As RibbonButton
            Get
                Return _ButtonOpen
            End Get
        End Property
        Private _ButtonAbout As RibbonButton
        Public ReadOnly Property ButtonAbout As RibbonButton
            Get
                Return _ButtonAbout
            End Get
        End Property
        Private _ButtonExit As RibbonButton
        Public ReadOnly Property ButtonExit As RibbonButton
            Get
                Return _ButtonExit
            End Get
        End Property
        Private _ButtonStartPage As RibbonButton
        Public ReadOnly Property ButtonStartPage As RibbonButton
            Get
                Return _ButtonStartPage
            End Get
        End Property
        Private _ButtonSave As RibbonButton
        Public ReadOnly Property ButtonSave As RibbonButton
            Get
                Return _ButtonSave
            End Get
        End Property
        Private _RibbonEditor As RibbonTabGroup
        Public ReadOnly Property RibbonEditor As RibbonTabGroup
            Get
                Return _RibbonEditor
            End Get
        End Property
        Private _MenuEditor As RibbonTab
        Public ReadOnly Property MenuEditor As RibbonTab
            Get
                Return _MenuEditor
            End Get
        End Property
        Private _GroupCodeFile As RibbonGroup
        Public ReadOnly Property GroupCodeFile As RibbonGroup
            Get
                Return _GroupCodeFile
            End Get
        End Property
        Private _ButtonSaveCodeFile As RibbonButton
        Public ReadOnly Property ButtonSaveCodeFile As RibbonButton
            Get
                Return _ButtonSaveCodeFile
            End Get
        End Property
        Private _GroupEditor As RibbonGroup
        Public ReadOnly Property GroupEditor As RibbonGroup
            Get
                Return _GroupEditor
            End Get
        End Property
        Private _ButtonGotoLine As RibbonButton
        Public ReadOnly Property ButtonGotoLine As RibbonButton
            Get
                Return _ButtonGotoLine
            End Get
        End Property
        Private _ButtonEditorDiff As RibbonButton
        Public ReadOnly Property ButtonEditorDiff As RibbonButton
            Get
                Return _ButtonEditorDiff
            End Get
        End Property
        Private _ButtonEditorSymbols As RibbonButton
        Public ReadOnly Property ButtonEditorSymbols As RibbonButton
            Get
                Return _ButtonEditorSymbols
            End Get
        End Property
        Private _GroupEditorMics As RibbonGroup
        Public ReadOnly Property GroupEditorMics As RibbonGroup
            Get
                Return _GroupEditorMics
            End Get
        End Property
        Private _ButtonEditorTheme As RibbonButton
        Public ReadOnly Property ButtonEditorTheme As RibbonButton
            Get
                Return _ButtonEditorTheme
            End Get
        End Property
        Private _MenuEdit As RibbonTab
        Public ReadOnly Property MenuEdit As RibbonTab
            Get
                Return _MenuEdit
            End Get
        End Property
        Private _GroupFile As RibbonGroup
        Public ReadOnly Property GroupFile As RibbonGroup
            Get
                Return _GroupFile
            End Get
        End Property
        Private _GroupSave As RibbonGroup
        Public ReadOnly Property GroupSave As RibbonGroup
            Get
                Return _GroupSave
            End Get
        End Property
        Private _ButtonSaveAs As RibbonButton
        Public ReadOnly Property ButtonSaveAs As RibbonButton
            Get
                Return _ButtonSaveAs
            End Get
        End Property
        Private _ButtonSaveAll As RibbonButton
        Public ReadOnly Property ButtonSaveAll As RibbonButton
            Get
                Return _ButtonSaveAll
            End Get
        End Property
        Private _GroupWorkbench As RibbonGroup
        Public ReadOnly Property GroupWorkbench As RibbonGroup
            Get
                Return _GroupWorkbench
            End Get
        End Property

        Public Sub New(ByVal ribbon As Ribbon)
            If ribbon Is Nothing Then
                Throw New ArgumentNullException(NameOf(ribbon), "Parameter is Nothing")
            End If
            _ribbon = ribbon
            _ButtonNew = New RibbonButton(_ribbon, Cmd.cmdButtonNew)
            _ButtonOpen = New RibbonButton(_ribbon, Cmd.cmdButtonOpen)
            _ButtonAbout = New RibbonButton(_ribbon, Cmd.cmdButtonAbout)
            _ButtonExit = New RibbonButton(_ribbon, Cmd.cmdButtonExit)
            _ButtonStartPage = New RibbonButton(_ribbon, Cmd.cmdButtonStartPage)
            _ButtonSave = New RibbonButton(_ribbon, Cmd.cmdButtonSave)
            _RibbonEditor = New RibbonTabGroup(_ribbon, Cmd.cmdRibbonEditor)
            _MenuEditor = New RibbonTab(_ribbon, Cmd.cmdMenuEditor)
            _GroupCodeFile = New RibbonGroup(_ribbon, Cmd.cmdGroupCodeFile)
            _ButtonSaveCodeFile = New RibbonButton(_ribbon, Cmd.cmdButtonSaveCodeFile)
            _GroupEditor = New RibbonGroup(_ribbon, Cmd.cmdGroupEditor)
            _ButtonGotoLine = New RibbonButton(_ribbon, Cmd.cmdButtonGotoLine)
            _ButtonEditorDiff = New RibbonButton(_ribbon, Cmd.cmdButtonEditorDiff)
            _ButtonEditorSymbols = New RibbonButton(_ribbon, Cmd.cmdButtonEditorSymbols)
            _GroupEditorMics = New RibbonGroup(_ribbon, Cmd.cmdGroupEditorMics)
            _ButtonEditorTheme = New RibbonButton(_ribbon, Cmd.cmdButtonEditorTheme)
            _MenuEdit = New RibbonTab(_ribbon, Cmd.cmdMenuEdit)
            _GroupFile = New RibbonGroup(_ribbon, Cmd.cmdGroupFile)
            _GroupSave = New RibbonGroup(_ribbon, Cmd.cmdGroupSave)
            _ButtonSaveAs = New RibbonButton(_ribbon, Cmd.cmdButtonSaveAs)
            _ButtonSaveAll = New RibbonButton(_ribbon, Cmd.cmdButtonSaveAll)
            _GroupWorkbench = New RibbonGroup(_ribbon, Cmd.cmdGroupWorkbench)
        End Sub

    End Class
End Namespace
